name: Deploy to GitHub pages

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [main]

env:
  BUILD_FOLDER: dist # or .output/public/yourrepositoryname/
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with private NPM package
        run: |
          echo "@theinsideline:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ env.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Build Vue App
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'

      - run: |
          npm install
          npm run build
          cp ./load-script.js ./dist/install.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{env.BUILD_FOLDER}}
          branch: ${{env.BRANCH}}
